export const ANNOUNCEMENTS_REQUEST = 'announcement/ANNOUNCEMENTS_REQUEST';
export const ANNOUNCEMENTS_SUCCESS = 'announcement/ANNOUNCEMENTS_SUCCESS';
export const ANNOUNCEMENTS_FAILURE = 'announcement/ANNOUNCEMENTS_FAILURE';
