export const ATTENDANCE_TEACHER_REQUEST = 'attendanceTeacher/ATTENDANCE_TEACHER_REQUEST';
export const ATTENDANCE_TEACHER_SUCCESS = 'attendanceTeacher/ATTENDANCE_TEACHER_SUCCESS';
export const ATTENDANCE_TEACHER_FAILURE = 'attendanceTeacher/ATTENDANCE_TEACHER_FAILURE';
