export const LOGIN_MOBILE_REQUEST = 'auth/LOGIN_MOBILE_REQUEST';

export const PROFILE_REQUEST = 'auth/PROFILE_MOBILE_REQUEST';
export const TEACHER_PROFILE_REQUEST = 'auth/PROFILE_TEACHER_REQUEST';
export const INSTITUTE_PROFILE_REQUEST = 'auth/INSTITUTE_PROFILE_REQUEST';

export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const LOG_OUT = 'auth/LOG_OUT';

export const VERIFY_INSTITUTE_REQUEST = 'institute/VERIFY_INSTITUTE_REQUEST';
export const VERIFY_INSTITUTE_SUCCESS = 'institute/VERIFY_INSTITUTE_SUCCESS';
export const VERIFY_INSTITUTE_FAILURE = 'institute/VERIFY_INSTITUTE_FAILURE';

export const REGISTER_INSTITUTE_REQUEST = 'institute/REGISTER_INSTITUTE_REQUEST';
export const REGISTER_INSTITUTE_SUCCESS = 'institute/REGISTER_INSTITUTE_SUCCESS';
export const REGISTER_INSTITUTE_FAILURE = 'institute/REGISTER_INSTITUTE_FAILURE';

export const INSTITUTE_REQUEST = 'institute/INSTITUTE_REQUEST';
export const INSTITUTE_SUCCESS = 'institute/INSTITUTE_SUCCESS';
export const INSTITUTE_FAILURE = 'institute/INSTITUTE_FAILURE';

export const SEND_OTP_REQUEST = 'auth/SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'auth/SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'auth/SEND_OTP_FAILURE';

export const VERIFY_OTP_REQUEST = 'auth/VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'auth/VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'auth/VERIFY_OTP_FAILURE';

export const SIBLINGS_REQUEST = 'siblings/SIBLINGS_REQUEST';
export const SIBLINGS_SUCCESS = 'siblings/SIBLINGS_SUCCESS';
export const SIBLINGS_FAILURE = 'siblings/SIBLINGS_FAILURE';

export const SAVE_INSTITUTE = 'institute/SAVE_INSTITUTE';
export const SWITCH_SIBLINGS_REQ = 'siblings/SWITCH_SIBLINGS_REQ';
export const SWITCH_SIBLINGS_SUCCESS = 'siblings/SWITCH_SIBLINGS_SUCCESS';
export const SWITCH_SIBLINGS_FAILURE = 'siblings/SWITCH_SIBLINGS_FAILURE';


