export const CLASS_HOMEWORK_GET_REQ = 'class/CLASS_HOMEWORK_GET_REQ';
export const CLASS_HOMEWORK_GET_SUCCESS = 'class/CLASS_HOMEWORK_GET_SUCCESS';
export const CLASS_HOMEWORK_GET_FAILURE = 'class/CLASS_HOMEWORK_GET_FAILURE';