export const CLASS_CLASSWORK_GET_REQ = 'class/CLASS_CLASSWORK_GET_REQ';
export const CLASS_CLASSWORK_GET_SUCCESS = 'class/CLASS_CLASSWORK_GET_SUCCESS';
export const CLASS_CLASSWORK_GET_FAILURE = 'class/CLASS_CLASSWORK_GET_FAILURE';