export const CLASS_ASSIGNMENT_GET_REQ = 'class/CLASS_ASSIGNMENT_GET_REQ';
export const CLASS_ASSIGNMENT_GET_SUCCESS = 'class/CLASS_ASSIGNMENT_GET_SUCCESS';
export const CLASS_ASSIGNMENT_GET_FAILURE = 'class/CLASS_ASSIGNMENT_GET_FAILURE';