export const LEARN_WITH_VIDEO_REQUEST = 'home/LEARN_WITH_VIDEO_REQUEST';
export const LEARN_WITH_VIDEO_SUCCESS = 'home/LEARN_WITH_VIDEO_SUCCESS';
export const LEARN_WITH_VIDEO_FAILURE = 'home/LEARN_WITH_VIDEO_FAILURE';
