export const NOTIFICATIONS_REQUEST = 'notification/NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_SUCCESS = 'notification/NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'notification/NOTIFICATIONS_FAILURE';
