export const RECOMMENDED_LESSONS_REQUEST = 'learn/RECOMMENDED_LESSONS_REQUEST';
export const RECOMMENDED_LESSONS_SUCCESS = 'learn/RECOMMENDED_LESSONS_SUCCESS';
export const RECOMMENDED_LESSONS_FAILURE = 'learn/RECOMMENDED_LESSONS_FAILURE';
