export const TEACHER_LEAVE_APPROVAL_REQUEST = 'studentLeave/TEACHER_LEAVE_APPROVAL_REQUEST';
export const TEACHER_LEAVE_APPROVAL_SUCCESS = 'studentLeave/TEACHER_LEAVE_APPROVAL_SUCCESS';
export const TEACHER_LEAVE_APPROVAL_FAILURE = 'studentLeave/TEACHER_LEAVE_APPROVAL_FAILURE';
