export const TEACHER_TIME_TABLE_REQUEST = 'scheduleTeacher/TEACHER_TIME_TABLE_REQUEST';
export const TEACHER_TIME_TABLE_SUCCESS = 'scheduleTeacher/TEACHER_TIME_TABLE_SUCCESS';
export const TEACHER_TIME_TABLE_FAILURE = 'scheduleTeacher/TEACHER_TIME_TABLE_FAILURE';
