export const TRENDING_CHAPTER_REQUEST = 'home/TRENDING_CHAPTER_REQUEST';
export const TRENDING_CHAPTER_SUCCESS = 'home/TRENDING_CHAPTER_SUCCESS';
export const TRENDING_CHAPTER_FAILURE = 'home/TRENDING_CHAPTER_FAILURE';
