export const botResponses = {
  choices: [
    {
      isFirst: true,
      text: 'Hello',
      botReply: "Hi, I'm here to help. What do you want to learn?",
      type: 'choice',
      choices: ['APIs', 'Javascript', 'Python', 'Java', 'Security'],
    },
    {
      isFirst: false,
      text: 'Yes',
      botReply: 'Great! How can I assist you?',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'APIs',
      botReply: 'Your Selected APIs',
      type: 'button',
      choices: ['Introduction of APIs', 'Guide of APIs'],
    },
    {
      isFirst: false,
      text: 'Javascript',
      botReply: 'Your Selected Javascript',
      type: 'button',
      choices: ['Introduction of Javascript', 'Guide of Javascript'],
    },
    {
      isFirst: false,
      text: 'Python',
      botReply: 'Your Selected Python',
      type: 'button',
      choices: ['Introduction of Python', 'Guide of Python'],
    },
    {
      isFirst: false,
      text: 'Java',
      botReply: 'Your Selected Java',
      type: 'button',
      choices: ['Introduction of Java', 'Guide of Java'],
    },
    {
      isFirst: false,
      text: 'Security',
      botReply: 'Your Selected Security',
      type: 'button',
      choices: ['Introduction of Security', 'Guide of Security'],
    },
    {
      isFirst: false,
      text: 'Introduction of APIs',
      botReply: 'Welcome to APIs Course',
      type: 'button',
      choices: ["What's APIs?", 'How to create APIs?'],
    },
    {
      isFirst: false,
      text: "What's APIs?",
      botReply: 'APIs is blablablba',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'No',
      botReply: 'Alright. If you change your mind, feel free to ask me anything.',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'Maybe',
      botReply: 'Sure. Take your time to think about it and let me know if you have any questions.',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'Thank you',
      botReply: "You're welcome! If you have any other questions, feel free to ask.",
      type: 'text',
    },
    {
      isFirst: false,
      text: 'Hi',
      botReply: 'Hello! How can I assist you today?',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'Good morning',
      botReply: 'Good morning! How can I assist you today?',
      type: 'text',
    },
    {
      isFirst: false,
      text: 'Good afternoon',
      botReply: 'Good afternoon! How may I help you?',
      type: 'text',
    },
  ],
};
