export * from './announcement';
export * from './attendance';
export * from './events';
export * from './feesDetails';
export * from './homework';
export * from './hostel';
export * from './interactiveClasses';
export * from './leave';
export * from './library';
export * from './liveClasses';
export * from './results';
export * from './syllabus';
export * from './timetable';
export * from './progress';
export * from './videoClasses'
export * from './viewAllTrending'
export * from './courseInformation'
export * from './otpScreen'
export * from './homeworkDetails'